//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.ServiceReferenceCatalogoProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCatalogoProducto.IServiceCatalogoProducto")]
    public interface IServiceCatalogoProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogoProducto/RecuperarCatalogo", ReplyAction="http://tempuri.org/IServiceCatalogoProducto/RecuperarCatalogoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Proyecto_ENT.CatalogoProducto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        Proyecto_ENT.Result RecuperarCatalogo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogoProducto/RecuperarCatalogo", ReplyAction="http://tempuri.org/IServiceCatalogoProducto/RecuperarCatalogoResponse")]
        System.Threading.Tasks.Task<Proyecto_ENT.Result> RecuperarCatalogoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogoProducto/RecuperarCatalogoGetById", ReplyAction="http://tempuri.org/IServiceCatalogoProducto/RecuperarCatalogoGetByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Proyecto_ENT.CatalogoProducto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        Proyecto_ENT.Result RecuperarCatalogoGetById(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogoProducto/RecuperarCatalogoGetById", ReplyAction="http://tempuri.org/IServiceCatalogoProducto/RecuperarCatalogoGetByIdResponse")]
        System.Threading.Tasks.Task<Proyecto_ENT.Result> RecuperarCatalogoGetByIdAsync(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogoProducto/AgregarProducto", ReplyAction="http://tempuri.org/IServiceCatalogoProducto/AgregarProductoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Proyecto_ENT.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Proyecto_ENT.CatalogoProducto))]
        Proyecto_ENT.Result AgregarProducto(Proyecto_ENT.CatalogoProducto catalogoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogoProducto/AgregarProducto", ReplyAction="http://tempuri.org/IServiceCatalogoProducto/AgregarProductoResponse")]
        System.Threading.Tasks.Task<Proyecto_ENT.Result> AgregarProductoAsync(Proyecto_ENT.CatalogoProducto catalogoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogoProducto/ActualizarProducto", ReplyAction="http://tempuri.org/IServiceCatalogoProducto/ActualizarProductoResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Proyecto_ENT.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Proyecto_ENT.CatalogoProducto))]
        Proyecto_ENT.Result ActualizarProducto(Proyecto_ENT.CatalogoProducto catalogoProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceCatalogoProducto/ActualizarProducto", ReplyAction="http://tempuri.org/IServiceCatalogoProducto/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<Proyecto_ENT.Result> ActualizarProductoAsync(Proyecto_ENT.CatalogoProducto catalogoProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceCatalogoProductoChannel : PL.ServiceReferenceCatalogoProducto.IServiceCatalogoProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceCatalogoProductoClient : System.ServiceModel.ClientBase<PL.ServiceReferenceCatalogoProducto.IServiceCatalogoProducto>, PL.ServiceReferenceCatalogoProducto.IServiceCatalogoProducto {
        
        public ServiceCatalogoProductoClient() {
        }
        
        public ServiceCatalogoProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceCatalogoProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogoProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceCatalogoProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Proyecto_ENT.Result RecuperarCatalogo() {
            return base.Channel.RecuperarCatalogo();
        }
        
        public System.Threading.Tasks.Task<Proyecto_ENT.Result> RecuperarCatalogoAsync() {
            return base.Channel.RecuperarCatalogoAsync();
        }
        
        public Proyecto_ENT.Result RecuperarCatalogoGetById(int IdProducto) {
            return base.Channel.RecuperarCatalogoGetById(IdProducto);
        }
        
        public System.Threading.Tasks.Task<Proyecto_ENT.Result> RecuperarCatalogoGetByIdAsync(int IdProducto) {
            return base.Channel.RecuperarCatalogoGetByIdAsync(IdProducto);
        }
        
        public Proyecto_ENT.Result AgregarProducto(Proyecto_ENT.CatalogoProducto catalogoProducto) {
            return base.Channel.AgregarProducto(catalogoProducto);
        }
        
        public System.Threading.Tasks.Task<Proyecto_ENT.Result> AgregarProductoAsync(Proyecto_ENT.CatalogoProducto catalogoProducto) {
            return base.Channel.AgregarProductoAsync(catalogoProducto);
        }
        
        public Proyecto_ENT.Result ActualizarProducto(Proyecto_ENT.CatalogoProducto catalogoProducto) {
            return base.Channel.ActualizarProducto(catalogoProducto);
        }
        
        public System.Threading.Tasks.Task<Proyecto_ENT.Result> ActualizarProductoAsync(Proyecto_ENT.CatalogoProducto catalogoProducto) {
            return base.Channel.ActualizarProductoAsync(catalogoProducto);
        }
    }
}
